version: '3.8'

services:
  loop-dune:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  loop-network:
    name: loop-network
    driver: bridge