version: '3.8'

services:
  sync:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DUNE_API_KEY=${DUNE_API_KEY}
      - ETH_RPC_URLS=${ETH_RPC_URLS}
      - BLOCK_PERIOD=${BLOCK_PERIOD:-1000}
      - BLOCK_RETRIEVAL_PERIOD=${BLOCK_RETRIEVAL_PERIOD:-0.1}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3